# Generated by Django 5.1.5 on 2025-01-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homefinder', '0002_alter_listing_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
